name: Test

on:
  push:
    branches:
      - trunk
      - develop
  pull_request:
    branches:
      - develop

jobs:
  cypress:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        core: ['latest', 'WordPress/WordPress#master']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm i

    - name: Build asset
      run: npm run build

    - name: Set the core version
      run: ./tests/bin/set-core-version ${{ matrix.core }}

    - name: Set up WP environment
      run: npm run env start

    - name: Test
      run: npm run cypress:run
